name: Arcade
version: '${version}'
main: com.pwdim.arcade.core.Arcade
description: §bMinigame Arcade
author: pwdim
depend:
  - SlimeWorldManager
commands:
  game:
    description: game
    permission: arcade.manage
  murder:
    description: play murder
    permission: ""
    aliases:
      - play
      - playmurder
      - murderjoin
  lobby:
    description: Voltar ao lobby
    permission: ""
    aliases:
      - l
      - hub
      - leave
      - back
  rooms:
    description: Gerenciar salas
    permission: arcade.manage
    aliases:
      - room
      - arenalist
      - manageroom
      - salas
      - rmenu
  roomcreate:
    description: Criar salas
    permission: arcade.manage
    aliases:
      - createroom
      - criarsala
      - novasala
  roomremove:
    description: Remover salas
    permission: arcade.manage
    aliases:
      - roomdelete
      - roomremove
      - removeroom
      - removersala
      - droproom
  debug:
    description: debug command
    permission: arcade.manage
